openshift/build-machinery-go

- make/lib/golang.mk
kube requires go 1.13.4 https://github.com/kubernetes/kubernetes/blob/7a1eaa1/hack/lib/golang.sh#L470
/cc @mfojtik
> Match kube go version requirements

- make/targets/openshift/deps-gomod.mk
/cc @mfojtik 
@openshift/sig-master @openshift/openshift-team-etcd @openshift/openshift-team-developer-experience I recommend bumping build-machinery-go when you bump your next dep, as this is limited to checking dependencies, immediate bump isn't required given you'd need special BZ
> Fix verify-deps exit code

- make/targets/openshift/deps-gomod.mk
> fix verify-deps always returning 1

- go.mod
- make/operator.example.mk.help.log
- make/targets/openshift/operator/telepresence.mk
- scripts/run-telepresence.sh
Check the comment header of `run-telepresence.sh` for instructions on use.
Canary:
- https://github.com/openshift/cluster-authentication-operator/pull/276
> Add make target and helper script to run operators with telepresence

- make/targets/openshift/crd-schema-gen.mk
The script to verify CRD codegen checks diffs only against files that
end in exactly `.crd.yaml`. This loosens that to just `crd.yaml` (with
no leading `.`) to ensure all CRDs are captured.
There are very few English words ending in `crd`, so I don't think there
is a risk of this conflicting.
> Loosen extension check for CRD verify script

- make/lib/golang.mk
Requires https://github.com/openshift/release/pull/10562
https://github.com/kubernetes/kubernetes/blob/05ffc95/hack/lib/golang.sh#L470
/cc @sttts @marun 
@openshift/sig-master you get it when you bump
> Bump min golang version to 1.14.4 for kubernetes 1.19

- make/examples/multiple-binaries/Makefile.test
- make/examples/multiple-binaries/Makefile.test.log
- make/examples/multiple-binaries/manifests/operator.openshift.io_myv1resources.crd.yaml
- make/examples/multiple-binaries/manifests/operator.openshift.io_myv1resources.crd.yaml-patch
- make/examples/multiple-binaries/pkg/apis/v1/register.go
- make/examples/multiple-binaries/pkg/apis/v1/types.go
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myv1resources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myv1resources.crd.yaml-patch
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myv1resources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myv1resources.crd.yaml-patch
- make/targets/openshift/controller-gen.mk
- make/targets/openshift/crd-schema-gen.mk
- make/targets/openshift/yaml-patch.mk
YAML merge patches cannot patch discriminated lists like CRDs' versions in v1. Hence, we need a more powerful patch format that can. https://github.com/krishicks/yaml-patch is the tool, following the semantics of json-patch.
Proof PR https://github.com/openshift/api/pull/720.
> Add *.yaml-patch support for CRDs + bump to controller-gen v0.2.5

- make/targets/openshift/crd-schema-gen.mk
The verify-codegen-crds target should compare the CRDs generating in the temp directory against the CRDs in the output directory rather than against the CRDs in the manifests directory.
> crd-schema-gen: verify against output instead of manifests

- make/lib/golang.mk
When ART builds an image, it copies the content of the source (github) repo into a production repo, and builds from that. The added SOURCE_GIT_* vars in Dockerfile are intended to relay the state of the *original* source repo, in case that is important at build or runtime.
To get the production version, one needs to read OS_GIT_VERSION instead.
Before:
```
go build -mod=vendor -trimpath -ldflags
"-s -w -X
github.com/openshift/cluster-kube-controller-manager-operator/pkg/version.versionFromGit="v0.0.0-alpha.0-897-gd95b645"
-X
github.com/openshift/cluster-kube-controller-manager-operator/pkg/version.commitFromGit="d95b6453"
-X
github.com/openshift/cluster-kube-controller-manager-operator/pkg/version.gitTreeState="dirty"
-X
github.com/openshift/cluster-kube-controller-manager-operator/pkg/ver …
```
> bug 1911211: Prefer OS_GIT_VERSION over SOURCE_GIT_TAG when getting build version

- make/examples/multiple-binaries/Makefile.test.log
- make/examples/multiple-binaries/profile-manifests-1/operator.deployment-profile1.yaml
- make/examples/multiple-binaries/profile-manifests-1/operator.deployment-profile2.yaml
- make/examples/multiple-binaries/profile-manifests-1/operator.service-profile1.yaml
- make/examples/multiple-binaries/profile-manifests-1/operator.service-profile2.yaml
- make/examples/multiple-binaries/profile-manifests-2/operator.deployment-profile-a.yaml
- make/examples/multiple-binaries/profile-manifests-2/operator.deployment-profile-b.yaml
- make/examples/multiple-binaries/profile-manifests-2/operator.service-profile-a.yaml
- make/examples/multiple-binaries/profile-manifests-2/operator.service-profile-b.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-1/operator.deployment-profile1.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-1/operator.deployment-profile2.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-1/operator.service-profile1.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-1/operator.service-profile2.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-2/operator.deployment-profile-a.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-2/operator.deployment-profile-b.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-2/operator.service-profile-a.yaml
- make/examples/multiple-binaries/testing/profile-manifests/updated-2/operator.service-profile-b.yaml
- make/targets/openshift/operator/profile-manifests.mk
Adds comment to generated manifest files to make it clear that they were generated and should not be edited directly.
> Add 'GENERATED' comment to files produced by manifest patches

- README.md
(Is there a way to automatically determine what’s the right image to use?)
> Document use of registry.ci instead of the deprecated registry.svc.ci

- Makefile
- make/examples/multiple-binaries/Makefile.test.log
Given a log line like
```
/abc/github.com/openshift/build-machinery-go/abc/ /github.com/openshift/build-machinery-go/ /def/github.com/openshift/build-machinery-go/def/
```
currently the edit command produces
```
/github.com/openshift/build-machinery-go/def/
```
matching everything from the first `/` to the end of the line, obscuring the command and hiding possibly relevant changes.
Use `[^ ]*` instead of `.*` to at least _try to_ treat one path at a time; it might not be perfect but it's an improvement.
> Try to only strip local path prefixes _within_ an argument

- make/default.example.mk.help.log
- make/examples/golang-versions-check/_output/named-golang-versions
- make/operator.example.mk.help.log
- make/targets/openshift/imagebuilder.mk
- make/targets/openshift/images.mk
make/targets/openshift/images.mk references imagebuilder, which I didn't have. There are other convenient `ensure-*` targets, so I thought I would make one for this.
However, `imagebuilder` is a go tool, and as such should be installed via `go get`, which behaves unreliably/inconsistently depending on the go version, variables, and dependencies in the consuming environment. Therefore, rather than trying to install it automatically, we instead produce a useful error message.
If we find the tool is installed, we check the version and emit a warning if it doesn't match what's expected.
If we like this concept, I'd like to do the same for `kustomize`.
> ensure imagebuilder

- make/targets/openshift/deps-gomod.mk
`make verify-deps` should cleanup after itself and delete the directory in `/tmp` that it creates.  
When running `make verify-deps` inside of `openshift/origin` it fills up my `/tmp` disk space after two runs.
> make verify-deps should cleanup it's temp directory

- make/default.mk
- make/golang.mk
- make/operator.mk
- make/targets/golang/build.mk
- make/targets/golang/test-unit.mk
- make/targets/golang/verify-update.mk
- make/targets/golang/version.mk
- make/targets/openshift/controller-gen.mk
- make/targets/openshift/crd-schema-gen.mk
- make/targets/openshift/deps-glide.mk
- make/targets/openshift/deps-gomod.mk
- make/targets/openshift/deps.mk
- make/targets/openshift/imagebuilder.mk
- make/targets/openshift/operator/profile-manifests.mk
- make/targets/openshift/operator/telepresence.mk
- make/targets/openshift/rpm.mk
- make/targets/openshift/yaml-patch.mk
- make/targets/openshift/yq.mk
Including at the bottom was messing up some load-time evaluations. Stop doing that; and stop using a common `self_dir` variable. See #43 for details.
closes #43
> Fix include ordering

- make/targets/golang/verify-update.mk
It should be "verify-golint" and not "verify-govet".
> Fix a typo in .PHONY

- make/targets/golang/version.mk
I don't know what `.PHONE` does, but I'm pretty sure it wasn't intended.
> Fix a typo

- make/examples/multiple-binaries/Makefile.test.log
- make/targets/openshift/controller-gen.mk
- make/targets/openshift/kustomize.mk
- make/targets/openshift/yaml-patch.mk
- make/targets/openshift/yq.mk
We provide a `clean-$foo` target for helper tools -- `$foo` in:
- `controller-gen`
- `kustomize`
- `yaml-patch`
- `yq`
Since #48 / aa83de7 we're installing those helpers to files with versioned names -- e.g. `yq-2.4.0` rather than just `yq` -- so `make clean-yq` would leave behind other versions of `yq`.
With this commit, `make clean-$foo` will remove `${foo}*`, which should lasso all previous versions of a given helper, including one with the unversioned name, which better meets the consumer's expectation of what "clean $foo" should mean.
> `clean-foo` removes all versions of `foo`

- make/targets/openshift/images.mk
images.mk uses ensure-imagebuilder from imagebuilder.mk. Import it so consumers don't have to do so.
> Import imagebuilder.mk from images.mk

- make/targets/openshift/kustomize.mk
aa83de7d / #48 added versioning for helper binaries. However, for kustomize, it assumed the install script would create the binary with the versioned name, which it doesn't. So consumers trying to use `$(KUSTOMIZE)`, which will be `_output/tools/bin/kustomize-v4.1.3`, will fail because it's actually at `_output/tools/bin/kustomize`.
Furthermore, running `make ensure-kustomize` twice will cause the install script to fail because its target file already exists.
Fix.
> Fix versioned ensure-kustomize

- make/lib/golang.mk
go1.16 reports itself as
go version go1.16 linux/amd64
which the sed expression used for go_version fails to recognise.
This patch makes the third component optional.
Signed-off-by: Stephen Kitt <skitt@redhat.com>
> go_version: allow for versions with two components

- make/examples/multiple-binaries/Makefile.test.log
- make/targets/openshift/yaml-patch.mk
> make/targets/openshift/yaml-patch: fix missing repository

- .ci-operator.yaml
- make/examples/multiple-binaries/Makefile.test.log
- make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml
- make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml
- make/targets/openshift/controller-gen.mk
We bumped controller-gen in https://github.com/openshift/api/pull/1016 but this one was still using 0.6, we should align those. 
/assign @sttts
> Bump controller-gen to v0.7.0 to match openshift/api

- make/lib/golang.mk
Signed-off-by: zhujian <jiazhu@redhat.com>
Now if `git describe --long --tags --abbrev=7 --match 'v[0-9]*'` failed, when we execute a command, output will be
```
testcommand --version
testcommand version v0.0.0-unknown
```
This commit makes it to be:
```
testcommand --version
testcommand version v0.0.0-unknown-85affa2f
```
> Make git tag contain git commit if matching the tag failed

- Makefile
- make/examples/multiple-binaries/Makefile
- make/examples/multiple-binaries/Makefile.test
- make/examples/multiple-binaries/Makefile.test.log
- make/targets/openshift/crd-schema-gen.mk
Being able to generate output into an alternative, possibly temporary, directory is interesting, but it makes for output [like][1]:
```
...
diff -Naup './config/v1/0000_10_config-operator_01_ingress.crd.yaml' '/tmp/tmp.uG3ZAq6abW/0000_10_config-operator_01_ingress.crd.yaml'
diff -Naup './config/v1/0000_03_config-operator_01_proxy.crd.yaml' '/tmp/tmp.uG3ZAq6abW/0000_03_config-operator_01_proxy.crd.yaml'
...many lines of no-diff noise...
--- ./operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml	2022-03-09 21:33:08.000000000 +0000
+++ /tmp/tmp.4pZalfGr2h/0000_90_cluster_csi_driver_01_config.crd.yaml	2022-03-09 21:36:30.265253548 +0000
@@ -51,6 +51,7 @@ spec:
- csi.sharedresource.openshift.io
- diskplugin.csi.alibabacloud.com
- vpc.block.csi.ibm.io
+                - csi.nutanix.com …
```
> make/targets/openshift/crd-schema-gen: In-place verification

- make/examples/multiple-binaries/Makefile.test.log
- make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml
- make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
- make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml-patch
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
- make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml-patch
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
- make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml-patch
Its schema was not being generated during the test (because there was no entry in the input `.spec.versions` named "v1").
https://github.com/kubernetes-sigs/controller-tools/blob/1878064c4cdf7f4d0550bf67d39853e1276865ca/pkg/schemapatcher/gen.go#L368-L400
> Add missing spec.versions field to CRD test fixture.

- make/targets/openshift/crd-schema-gen.mk
This lets someone create 
`$(call add-crd-gen-for-featureset,example-alpha,./example/v1alpha1,./example/v1alpha1,./example/v1alpha1,TechPreviewNoUpgrade)`
in their Makefile.  This is the simplest thing that can work.  The securityinternal group has a patch file that does a remove.  We really want the patch target to skip files that don't match the featureset, but I can't figure out how to do that.  I don't want to block the overall feature on perfect makefile work.
> add the ability for techpreview generation per api group

- make/targets/golang/test-unit.mk
I have a use-case where I need to add test arguments in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1449#discussion_r1120912655 and this is not possible today with the existing machinery since args need to be provided after the packages.
> golang/test-unit: add go test args

- make/default.example.mk.help.log
- make/golang.example.mk.help.log
- make/operator.example.mk.help.log
- make/targets/golang/vulncheck.mk
- scripts/vulncheck.sh
With this commit, `make vulncheck` will emit a report similar to:
```
[
"golang.org/x/net",
"v0.5.0",
"v0.7.0"
]
[
"stdlib",
"go1.19.3",
"go1.20.1"
]
[
"stdlib",
"go1.19.3",
"go1.19.4"
]
```
Each stanza lists
- where the vulnerability exists
- the version it was found in
- the version it's fixed in
If the report contains any entries that are *not* in `stdlib`, the check will fail (exit nonzero). Otherwise it will succeed -- i.e. the `stdlib` entries are only warnings.
TODO: Include more useful information in each stanza, e.g. ID/URL.
> `vulncheck` for golang

- commitchecker/Makefile
- commitchecker/README.md
- commitchecker/commitchecker.go
- commitchecker/git.go
- commitchecker/git_test.go
- commitchecker/go.mod
- commitchecker/go.sum
- commitchecker/validate.go
- commitchecker/validate_test.go
Add commitchecker from the openshift/kubernetes repo and remove unused code. Moving it here makes it possible to vendor and/or `go get` the tool for use in other repos.
> Add commitchecker

- Dockerfile.commitchecker
- commitchecker/.gitignore
- commitchecker/commitchecker.go
- commitchecker/pkg/commitchecker/git.go
commitchecker: don't use an import alias
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
commitchecker: log what we're doing
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
commitchecker: use the ancestry-path
After we do our merge magic to reset the repo to the upstream state,
`git log` requires `--ancestry-path` to output meaningful data.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
commitchecker: ignore built binary
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
> commitchecker: more updates

- make/targets/golang/version.mk
Starting go 1.22, the go version in go.mod is formatted as MAJOR.MINOR.PATCH. For the purpose of verifying go version across go.mod, Dockerfile, ci-operator.yaml, only MAJOR.MINOR version is evaluated given go version in image tags from Docker and CI manifests are formatted as MAJOR.MAJOR only.
> Only use MAJOR.MINOR version for go version from go.mod

- scripts/test-operator-integration.sh
This is required because **-mod=vendor** is enforced in CI, so it tries to use the vendor directory for dependencies instead of fetching them from the internet.
Enforcing **-mod=readonly** means that the go command will ignore the vendor directory.
/assign @p0lyn0mial @deads2k
> API-1835: Add -mod=readonly when installing mom

- make/operator.example.mk.help.log
- make/targets/openshift/operator/mom.mk
- scripts/test-operator-integration.sh
adds `make update-test-operator-integration`
> API-1835: make it easy to replace operator integration output

- make/targets/openshift/images.mk
Make images.mk generic and not tied to imagebuilder. This will allow users to use other build tools such as podman and buildah.
> Make images.mk generic

- make/targets/openshift/controller-gen.mk
Though well-intentioned, controller-gen.mk is tough to maintain due to the need to build and publish binaries for multiple platforms at any desired release.
This PR does not change functionality, but leaves a deprecation comment in the source file with the idea that current consumers wishing to upgrade their controller-gen will find it after running into the same problems I did (see the issue).
Resolves #93
> Deprecate controller-gen.mk

- make/targets/golang/verify-update.mk
to prevent hitting the maximum argument limits when listing on an individual file basis.
> (bugfix): Run gofmt on files in chunks

- commitchecker/README.md
We stopped building individual images for each OCP branch. The commitchecker is now available with tag `latest` that should work with all OCP braches.
Example of usage: https://github.com/openshift/release/blob/a156c2b5993702463f56d17667aa23680bc13aaa/ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-master.yaml#L2-L5
> commitchecker: fix image tags in README
